image: Visual Studio 2017

init:
  - git config --global core.autocrlf input

build_script:
  - cmd: echo /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" >> msbuild.rsp
  - cmd: msbuild /t:configure /p:configuration=release
  - cmd: msbuild /t:build /p:configuration=release

nuget:
  disable_publish_on_pr: false
  
artifacts:
  - path: out\*.nupkg
    name: Package